### ISSUE TITLE
does not work with safari

### ISSUE THREAD

**Issue by adamwong246** [benjick/meteor-webcam#1]
I have tested webcamjs's demos in Safari and all seems good. However, in my meteor app, the flash fallback never loads
![screen shot 2015-09-01 at 1 01 05 pm](https://cloud.githubusercontent.com/assets/474792/9614895/8ab1957a-50a9-11e5-8117-12831fe3a8b7.png)

**Comment by benjick** [comment]
Does Safari have an equivalent to the network tab in Chrome developer tools? If so, can you check if the file is loaded? I think I see where the problem it

**Comment by adamwong246** [comment]
I used the `force_flash` option and reproduced this same issue in chrome. Both Chrome and safari seem to indicate that the webcam has the url `http://localhost:3000/webcam.swf` but that address 404s

**Comment by adamwong246** [comment]
Heres the solution https://github.com/jhuckaby/webcamjs#setting-an-alternate-swf-location

`Webcam.setSWFLocation("/packages/benjick_webcam/webcamjs/webcam.swf")`

**Comment by benjick** [comment]
Thanks. Is that URL accessible from the browser?

Feel free to send a PR
